#!/bin/bash

# Current date
currentDate=`date +%Y-%m-%d`
# Date year ago
dateYearAgo=`date "--date=${date} -1 year" +%Y-%m-%d`

counter=0
tmpDate=$dateYearAgo
# Offset
OffsetX=0
OffsetY=0
# Clear screen, set cursor position
tput clear;tput cup $OffsetX $OffsetY
week=0
while [ "$tmpDate" != "$currentDate" ]
do
    let "counter=$counter + 1"
    let "OffsetX=($counter/7) + 0"
    let "OffsetY=0 + $week"
    let "week=$week+1"

    tmpDate=`date "--date=$tmpDate +1 day" +%Y-%m-%d`
    tput cup $OffsetY $OffsetX;echo "0"
    if [ $week -eq 6 ]
    then
        week=0
    fi
done

echo $counter